name: Jaconda
slug: jaconda
access: public

description: "Jaconda is a chat service for project teams. Chat rooms are accessible through web browsers and instant messengers (using Google Talk). This app sends notifications for new tickets, replies and comments to a room in Jaconda"

category: notification

tags: 
- jaconda
- notification
- chat

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: "prateekdayal"
  github: prateekdayal
