name: Github Issues 
slug: github
access: public

description: "
Create an issue on Github Issues!

An agent can create an issue on Github for a particular ticket in SupportBee. You can customize the title/description before creating the issue.
"

category: project-management

tags:
- github
- issue tracking 

developer: 
  name: Anh Do
  email: anh@supportbee.com
  twitter: "@anhnk"
  github: anhnk

action:
  button:
    overlay: true
    screens:
    - ticket
    label: Send To Github
