name: ZohoCRM
slug: zoho_crm
access: public

description: "Pull customer information from Zoho and see it as a comment on the ticket with a link to the Zoho page."

category: crm

tags: 
- crm
- zoho

developer: 
  name: Shaikh Imran
  email: imranshaikh818@gmail.com
  twitter: "@imranshaikh_me"
  github: Imranshaikh

