name: Asana
slug: asana
access: public

description: "
Create a task on Asana!

An agent can create a task on Asana for a particular ticket in SupportBee Ticket screen.
"

category: project-management

tags:
- asana
- project management

developer: 
  name: Avinasha S
  email: avinasha@supportbee.com
  twitter: "@AviShastry"
  github: avinasha

action:
  button:
    overlay: true
    screens:
    - ticket
    label: Send To Asana
