name: Evernote
slug: evernote
access: public

description: "Sends your tickets and replies to a notebook in evernote"

category: Organizer

tags: 
- evernote
- sync

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: "prateekdayal"
  github: prateekdayal

# The following config keys are used by Action Handlers
# Set button 'overlay' to true, if you want to have an overlay
# The valid values for screens are [ticket, all, unassigned, my, groups]
# Remove the following section if you do not want to define Action Handlers
